### ISSUE TITLE
Service API

### ISSUE THREAD

**Issue by Kuroidaka** [Kuroidaka/WDM_BE#6]
Tạo CRUD API cho tính năng services

**Comment by letanhoaUIT** [comment]
-- GET SERVICE

![Image](https://github.com/Kuroidaka/WDM_BE/assets/141432034/d7f3ad02-34f1-44b3-800d-ebb5fcbd36fb)




-- POST SERVICE

![Image](https://github.com/Kuroidaka/WDM_BE/assets/141432034/39953c0b-9412-4e47-8aaa-9e8501da814d)

**Comment by Kuroidaka** [comment]
Thiếu cái API để edit service rồi daika

**Comment by letanhoaUIT** [comment]
--UPDATE SERVICE--
<img width="643" alt="image" src="https://github.com/Kuroidaka/WDM_BE/assets/141432034/3322ed4c-dca7-42e9-8372-c5e308b98eb1">
** error message: service not found for update
<img width="629" alt="image" src="https://github.com/Kuroidaka/WDM_BE/assets/141432034/62bebca8-8cbb-4317-8624-dbd3bd76454e">

**Comment by letanhoaUIT** [comment]
-- DELETE SERVICE --
<img width="632" alt="image" src="https://github.com/Kuroidaka/WDM_BE/assets/141432034/0c36adbe-72d5-4f1f-b76f-923980f05970">
