### ISSUE TITLE
Food API

### ISSUE THREAD

**Issue by Kuroidaka** [Kuroidaka/WDM_BE#8]
update delete and edit API for food feature

**Comment by letanhoaUIT** [comment]
Postman for update food:

![image](https://github.com/Kuroidaka/WDM_BE/assets/141432034/de2cb95c-e30e-4dbf-a2c1-45bc9e601796)

For delete food:
![image](https://github.com/Kuroidaka/WDM_BE/assets/141432034/b574b7a7-d43b-4828-a58b-13ea95eac0d4)
